openapi: 3.0.0
tags:
  - name: Articles
get:

  description: Test
responses:
    '200':
      description: Successful response
    '400':
      description: Bad Request
    '500':
      description: Internal Server Error